from . import rest_htask
from . import hotel
from . import hotel_booking
from . import hotel_booking_line
from . import room_type
from . import hotel_rate_plan
from . import hotel_rate_type
from . import ezee_rate_type
from . import ezee_room_type
from . import ezee_rate_plan
from . import ezee_extra_charge
from . import hotel_services
from . import booking_folio
from . import audit_trails
