from . import booking_apply_discount
from . import booking_filter
from . import booking_group_action
from . import booking_payment_register
from . import booking_refund_payment
from . import daily_revenue
from . import daily_revenue_by_room_type
from . import daily_revenue_by_rate_plan
from . import daily_revenue_by_tax
from . import daily_tax
from . import folio_amend_stay
from . import folio_change_room
from . import folio_filter
from . import folio_report
from . import folio_room_charge
from . import folio_service
from . import night_audit
from . import revenue_summary
from . import room_type_availability_report
from . import trial_balance_wizard
from . import warn_wizard
from . import room_charge_wizard
from . import guest_ledger
from . import hotel_manager_report
from . import cashier_summary_report
from . import  room_availability
