{
    'name': 'Hotel Booking Management',
    'version': '15.0.0',
    'description': """Hotel Management System""",
    'category': 'Base',
    'author': 'Hotels Task',
    'website': "https://www.hotelstask.com",
    'license': 'AGPL-3',
    'depends': [
        'account', 'product', 'text_table_widget', 'contacts', 'purchase', 'web_domain_field', 'hr',
        'sh_whatsapp_integration_api', 'multi_step_wizard', 'saudi_einvoice_knk', 'einv_sa','report_xlsx'
    ],
    'data': [
        'security/group.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        # 'data/floors.xml',
        # 'data/room_type.xml',
        # 'data/rooms.xml',
        'data/facility.xml',
        'data/product.xml',
        'data/sequence.xml',
        'data/mail.xml',
        'data/res_company.xml',
        'data/room_stay_over_status.xml',
        'data/server_action.xml',
        'data/cron.xml',
        'data/payment_methods.xml',
        'data/booking.source.csv',
        'views/hotel.xml',
        'views/floor.xml',
        'views/res_company.xml',
        'views/housekeeping.xml',
        'views/hotel_work_order.xml',
        'views/booking_folio_line.xml',
        'views/advance_payment_view.xml',
        'views/out_of_order.xml',
        'views/hotel_room_type.xml',
        'views/room_status.xml',
        'views/rate_type.xml',
        'views/rate_plan.xml',
        'views/room_type.xml',
        'views/facility.xml',
        'views/room.xml',
        'views/booking.xml',
        # 'views/menus.xml',
        'views/res_partner.xml',
        'views/account_move.xml',
        'views/account_move_line.xml',
        'views/dashboard2.xml',
        'views/transfer.xml',
        'views/conditions.xml',
        'views/services.xml',
        'views/email.xml',
        'reports/report.xml',
        'reports/booking_report.xml',
        'reports/housekeeping_report.xml',
        'reports/booking_filter.xml',
        'reports/invoice.xml',
        'reports/guest_reg_form_report.xml',
        'reports/payment_report.xml',
        'views/contract.xml',
        'views/purchase.xml',
        'views/bed_type.xml',
        'views/out_of_order_reason.xml',
        'views/booking_type.xml',
        'views/booking_source.xml',
        'views/booking_folio.xml',
        'views/booking_discount.xml',
        'views/booking_filter.xml',
        'views/settled_booking_view.xml',
        'views/booking_portal_template.xml',
        'views/account_payment.xml',
        'views/season_duration.xml',
        'views/account_journal.xml',
        'views/hr_employee.xml',
        'views/city_ledger_payment.xml',
        'views/market_segmentation.xml',
        'wizards/account_payment_wizard.xml',
        'wizards/city_ledger_wizard.xml',
        'wizards/booking_arrival_xlsx.xml',
        'wizards/update_room_status.xml',
        'wizards/booking_apply_discount.xml',
        'wizards/booking_payment_register.xml',
        'wizards/night_audit.xml',
        'wizards/booking_cancel.xml',
        'wizards/partner_ledger_wizard.xml',
        'wizards/account_move_line_report.xml',
        'wizards/booking_folio_wizard.xml',
        'wizards/booking_arrival.xml',
        'wizards/booking_departure.xml',
        'wizards/actual_checkin.xml',
        'wizards/actual_departure.xml',
        'wizards/hotel_service.xml',
        'wizards/room_status.xml',
        'wizards/work_order.xml',
        'wizards/booking_cancellation.xml',
        'wizards/hotel_booking_source.xml',
        'wizards/room_type_reservied.xml',
        'wizards/payment_folio_refund.xml',
        'wizards/revenue_rate_plan.xml',
        'wizards/revenue_room_type.xml',
        'wizards/booking_reservation.xml',
        'wizards/complimentary_reservation.xml',
        'wizards/company_booking_source_report.xml',
        'wizards/housekeeping_diff.xml',
        'wizards/company_ledger_report_view.xml',
        'wizards/sason_productivity_view.xml',
        'reports/housekeeping_diff_report.xml',
        'reports/city_ledger_report.xml',
        'reports/account_payment_custom_report.xml',
        'reports/booking_source_report.xml',
        'reports/work_order_report.xml',
        'reports/booking_cancellation.xml',
        'reports/room_status_report.xml',
        'reports/hotel_services_report.xml',
        'reports/actual_departure.xml',
        'reports/account_payment_report.xml',
        'reports/folio_payment_report.xml',
        'reports/booking_folio_report.xml',
        'reports/booking_departure.xml',
        'reports/booking_arrival.xml',
        'reports/actual_checkin.xml',
        'reports/booking_departure.xml',
        'reports/folio_report.xml',
        'reports/guest_register_form.xml',
        'reports/booking_tree.xml',
        'reports/invoice_template.xml',
        'reports/room_type_recervied.xml',
        'reports/payment_folio_refund.xml',
        'reports/revenue_rate_plan.xml',
        'reports/revenue_room_type.xml',
        'reports/booking_filter_xlsx.xml',
        'reports/dynamic_booking_source_report.xml',
        'reports/booking_reservation.xml',
        'reports/complimentary_reservation.xml',
        'reports/electronic_invoice_template.xml',
        'reports/vat_invoice_report_print.xml',
        'reports/simpli_vat_invoice_report.xml',
        'reports/partner_ledger_report.xml',
        'reports/company_ledger_report.xml',
        'reports/company_booking_source_report.xml',
        'reports/season_productivity_report.xml'
    ],
    'external_dependencies': {
        'python': ['hijri_converter'],
    },
    'assets': {
        'web.assets_backend': [
            'hotel_booking/static/src/js/room_kanban.js',
            'hotel_booking/static/src/js/housekeeping_diff_report_list_controller.js',
            'hotel_booking/static/src/js/housekeeping_diff_report_list_view.js',
            # 'hotel_booking/static/src/js/confirm_save.js',
        ],
        'web.assets_qweb': [
            'hotel_booking/static/src/xml/housekeeping_diff_report.xml'
        ]
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}
