from . import res_company
from . import shomoos_nationality
from . import shomoos_country
from . import shomoos_identity_type
from . import booking_folio
from . import shomoos_response_code
from . import audit_trails
from . import hotel_booking
from . import res_partner
