from odoo import models, fields, api

class ResUsers(models.Model):
    _inherit = 'res.users'

    role_type = fields.Selection([
        ('admin', 'Administrator'),
        ('account', 'Accountant'),
        ('front', 'FrontOffice'),
        ('night', 'NightAuditor'),
        ('house', 'HouseKeeping'),
    ], string='Role Type')

    # Utility method to get role-to-groups mapping
    def _get_role_group_ids(self, role_key):
        group_map = {
            'admin': [
                 'hotel_booking.group_allowed_discount',
                'hotel_booking.group_cancel_booking',
                'hotel_booking_folio.group_cancel_folios',
                'hotel_booking.group_create_company',
                'hotel_booking_folio.group_manager_report',
                'base.group_erp_manager',
                'hotel_booking_folio.group_update_room_charge_before_audit',
                'base.group_private_addresses',
                'base.group_allow_export',
                'sh_whatsapp_integration_api.group_account_whatsapp_feature',
                'account.group_account_user',
                'hotel_booking.accounting_reporting_group',
                'hotel_booking_folio.group_add_service',
                'hotel_booking.group_hotel_booking_admin',
                'point_of_sale.group_pos_manager',
                'hr.group_hr_manager',
                'sales_team.group_sale_manager',
                'stock.group_stock_manager',
                'purchase.group_purchase_manager',
                'account.group_account_manager',
                'hotel_booking.group_aiosell_connector_menu',
                'om_fiscal_year.group_fiscal_year',
                'analytic.group_analytic_accounting',
                'account.group_account_readonly',
                'product.group_product_pricelist',
                'account.group_account_invoice',
                'hotel_booking.menu_booking_customer_group',
                'hotel_booking.menu_booking_discount_group',
                'hotel_booking.payment_type_selection_group',
                'hotel_booking.menu_booking_source_group',
                'hotel_booking.booking_source_company_group',
                'hotel_booking.menu_business_source_group',
                'sh_whatsapp_integration_api.group_crm_whatsapp_msg_feature',
                'hotel_booking_folio.group_cancel_folio',
                'hotel_booking_folio.group_check_in',
                'hotel_booking_folio.group_check_in_exception',
                'hotel_booking_folio.group_check_without_settled',
                'hotel_booking_folio.group_check_out',
                'hotel_booking_folio.group_check_out_charge',
                'hotel_booking.company_contact_menu_group',
                'hotel_booking.htask_configuration_group',
                'hotel_booking_folio.group_confirm_folio',
                'base.group_partner_manager',
                'hotel_booking.contact_menu_group',
                'hotel_booking.create_out_of_order_group',
                'hotel_booking.create_work_order_group',
                'hotel_booking.customers_contact_menu_group',
                'hotel_booking.group_dashboard_booking_status',
                'hotel_booking.group_edit_amount_register_payment',
                'hotel_booking.edit_price_tax_group',
                'hotel_booking.edit_price_unit_group',
                'hotel_booking.extra_net_group',
                'hotel_booking.folio_filter_menu_group',
                'hotel_booking.front_office_group',
                'hotel_booking.front_office_report_menu',
                'hotel_booking.hotel_bed_type_menu',
                'hotel_booking.menu_hotel_conditions_group',
                'hotel_booking.hotel_facility_menu_group',
                'hotel_booking.menu_hotel_services_group',
                'hotel_booking.hotel_hotel_menu_group',
                'hotel_booking.housekeeping_group',
                'hotel_booking.housekeeping_menu_report',
                'base.group_user',
                'mail.group_mail_template_editor',
                'ks_curved_backend_theme.ks_curved_theme_settings',
                'hotel_booking.group_no_payment_check_in',
                'hotel_booking.market_segmentation_group',
                'base.group_multi_currency',
                'hotel_booking.ntmp_root_menu_group',
                'hotel_booking.night_audit_group',
                'hr.group_hr_user',
                'hotel_booking.out_of_order_group',
                'hotel_booking.menu_out_of_service_reason_group',
                'hotel_booking.menu_out_reason_group',
                'hotel_booking.group_pay_amount_register_payment',
                'hotel_booking.group_pay_max_credit',
                'sh_whatsapp_integration_api.group_purchase_whatsapp_feature',
                'hotel_booking.rate_plan_menu_group',
                'hotel_booking.rate_type_menu_group',
                'hotel_booking_folio.group_refund_payment',
                'hotel_booking_folio.group_register_payment',
                'hotel_booking.reporting_group',
                'hotel_booking.group_required_company_field',
                'hotel_booking.reservation_management_group',
                'hotel_booking.booking_type_group',
                'room_availability_dashboard.group_room_availability_dashboard',
                'hotel_booking.menu_room_status_group',
                'hotel_booking.menu_room_stay_status_group',
                'hotel_booking.menu_room_type_group',
                'hotel_booking.hotel_rooms_menu_group',
                'sh_whatsapp_integration_api.group_sales_whatsapp_feature',
                'sh_whatsapp_integration_api.group_send_whatsapp_quick',
                'purchase.group_send_reminder',
                'hotel_booking.group_set_notes_register_payment',
                'base.group_system',
                'hotel_booking.shomoos_root_menu_group',
                'sh_whatsapp_integration_api.group_stock_whatsapp_feature',
                'account.group_show_line_subtotals_tax_excluded',
                'base.group_no_one',
                'hotel_booking.group_update_audit_date',
                'hotel_booking.group_update_expiration_date',
                'hotel_booking.group_update_housekeeper',
                'hotel_booking.group_update_out_of_order',
                'hotel_booking.group_update_out_of_service',
                'hotel_booking_folio.group_update_charge_with_zero',
                'hotel_booking.group_update_status',
                'hotel_booking_folio.group_update_room_charge_user',
                'hotel_booking.group_delete_booking_user',
                'hotel_booking.group_amend_stay',
                'hotel_booking.group_add_package',
                'hotel_booking.group_change_room',
                'hotel_booking.group_assign_room',
                'hotel_booking.group_night_audit',
                'hotel_booking.group_booking_discount',
                'hotel_booking.group_hotel_booking_user',
                'hotel_booking_folio.group_change_room_charge_user',
                'hotel_booking_folio.group_daily_revenue_user',
                'hotel_booking_folio.group_undo_check_in_user',
                'hotel_booking_folio.group_undo_check_out_user',
                'purchase.group_purchase_user',
                'stock.group_stock_user',
                'point_of_sale.group_pos_user',
                'sales_team.group_sale_salesman_all_leads',
                'sales_team.group_sale_salesman',
                'sh_whatsapp_integration_api.sh_whatsapp_configuration_manager',
                'hotel_booking.work_orders_group'
            ],
            'account': [
                'hotel_booking.group_cancel_booking',
                'hotel_booking_folio.group_cancel_folios',
                'hotel_booking.group_create_company',
                'hotel_booking_folio.group_manager_report',
                'base.group_erp_manager',
                'base.group_private_addresses',
                'base.group_allow_export',
                'account.group_account_user',
                'hotel_booking.accounting_reporting_group',
                'hotel_booking_folio.group_add_service',
                'stock.group_stock_manager',
                'point_of_sale.group_pos_manager',
                'hr.group_hr_manager',
                'purchase.group_purchase_manager',
                'hotel_booking.group_hotel_booking_admin',
                'account.group_account_readonly',
                'product.group_product_pricelist',
                'account.group_account_invoice',
                'hotel_booking.menu_booking_customer_group',
                'hotel_booking.booking_source_company_group',
                'hotel_booking_folio.group_cancel_folio',
                'hotel_booking_folio.group_check_in',
                'hotel_booking_folio.group_check_out',
                'hotel_booking_folio.group_confirm_folio',
                'base.group_partner_manager',
                'hotel_booking.folio_filter_menu_group',
                'hotel_booking.front_office_group',
                'hotel_booking.front_office_report_menu',
                'base.group_user',
                'mail.group_mail_template_editor',
                'base.group_multi_currency',
                'hotel_booking.night_audit_group',
                'hr.group_hr_user',
                'hotel_booking_folio.group_register_payment',
                'hotel_booking.reporting_group',
                'hotel_booking.reservation_management_group',
                'room_availability_dashboard.group_room_availability_dashboard',
                'hotel_booking.hotel_rooms_menu_group',
                'purchase.group_send_reminder',
                'account.group_show_line_subtotals_tax_excluded',
                'base.group_no_one',
                'hotel_booking_folio.group_undo_check_in_user',
                'hotel_booking.group_hotel_booking_user',
                'purchase.group_purchase_user',
                'hotel_booking_folio.group_undo_check_out_user',
                'stock.group_stock_user',
                'point_of_sale.group_pos_user',
                'hotel_booking.group_night_audit',
                'sales_team.group_sale_salesman_all_leads',
                'sales_team.group_sale_salesman'
            ],
            'front': [
                'hotel_booking.group_cancel_booking',
                'hotel_booking_folio.group_cancel_folios',
                'hotel_booking.group_create_company',
                'base.group_erp_manager',
                'base.group_private_addresses',
                'base.group_allow_export',
                'hotel_booking_folio.group_add_service',
                'hotel_booking.group_hotel_booking_admin',
                'hr.group_hr_manager',
                'product.group_product_pricelist',
                'account.group_account_invoice',
                'hotel_booking.menu_booking_customer_group',
                'hotel_booking.payment_type_selection_group',
                'hotel_booking.booking_source_company_group',
                'hotel_booking_folio.group_cancel_folio',
                'hotel_booking_folio.group_check_in',
                'hotel_booking_folio.group_check_without_settled',
                'hotel_booking_folio.group_check_out',
                'hotel_booking.company_contact_menu_group',
                'hotel_booking_folio.group_confirm_folio',
                'base.group_partner_manager',
                'hotel_booking.create_out_of_order_group',
                'hotel_booking.create_work_order_group',
                'hotel_booking.customers_contact_menu_group',
                'hotel_booking.group_edit_amount_register_payment',
                'hotel_booking.edit_price_tax_group',
                'hotel_booking.edit_price_unit_group',
                'hotel_booking.folio_filter_menu_group',
                'hotel_booking.front_office_group',
                'hotel_booking.front_office_report_menu',
                'hotel_booking.housekeeping_group',
                'hotel_booking.housekeeping_menu_report',
                'base.group_user',
                'mail.group_mail_template_editor',
                'hotel_booking.group_no_payment_check_in',
                'base.group_multi_currency',
                'hr.group_hr_user',
                'hotel_booking.out_of_order_group',
                'hotel_booking.group_pay_amount_register_payment',
                'hotel_booking_folio.group_refund_payment',
                'hotel_booking_folio.group_register_payment',
                'hotel_booking.reporting_group',
                'hotel_booking.reservation_management_group',
                'room_availability_dashboard.group_room_availability_dashboard',
                'hotel_booking.hotel_rooms_menu_group',
                'purchase.group_send_reminder',
                'account.group_show_line_subtotals_tax_excluded',
                'base.group_no_one',
                'hotel_booking.group_update_housekeeper',
                'hotel_booking.group_update_out_of_order',
                'hotel_booking_folio.group_update_charge_with_zero',
                'hotel_booking.group_update_status',
                'hotel_booking.group_change_room',
                'hotel_booking.group_night_audit',
                'hotel_booking.group_hotel_booking_user',
                'hotel_booking_folio.group_undo_check_in_user',
                'hotel_booking_folio.group_undo_check_out_user',
                'hotel_booking_folio.group_update_room_charge_user',
                'hotel_booking.group_amend_stay',
                'sales_team.group_sale_salesman_all_leads',
                'sales_team.group_sale_salesman',
                'hotel_booking.work_orders_group',
            ],
            'night': [
                'hotel_booking.group_cancel_booking',
                'hotel_booking_folio.group_cancel_folios',
                'hotel_booking.group_create_company',
                'hotel_booking_folio.group_manager_report',
                'base.group_erp_manager',
                'base.group_private_addresses',
                'base.group_allow_export',
                'account.group_account_user',
                'hotel_booking.accounting_reporting_group',
                'hotel_booking_folio.group_add_service',
                'point_of_sale.group_pos_manager',
                'hr.group_hr_manager',
                'stock.group_stock_manager',
                'purchase.group_purchase_manager',
                'hotel_booking.group_hotel_booking_admin',
                'account.group_account_readonly',
                'room_type_availability_dashboard.group_room_type_availability_dashboard',
                'product.group_product_pricelist',
                'account.group_account_invoice',
                'hotel_booking.menu_booking_customer_group',
                'hotel_booking.payment_type_selection_group',
                'hotel_booking.booking_source_company_group',
                'hotel_booking_folio.group_cancel_folio',
                'hotel_booking_folio.group_check_in',
                'hotel_booking_folio.group_check_without_settled',
                'hotel_booking_folio.group_check_out',
                'hotel_booking.company_contact_menu_group',
                'hotel_booking_folio.group_confirm_folio',
                'base.group_partner_manager',
                'hotel_booking.contact_menu_group',
                'hotel_booking.create_out_of_order_group',
                'hotel_booking.create_work_order_group',
                'hotel_booking.customers_contact_menu_group',
                'hotel_booking.group_dashboard_booking_status',
                'hotel_booking.group_edit_amount_register_payment',
                'hotel_booking.edit_price_tax_group',
                'hotel_booking.edit_price_unit_group',
                'hotel_booking.folio_filter_menu_group',
                'hotel_booking.front_office_group',
                'hotel_booking.front_office_report_menu',
                'hotel_booking.housekeeping_group',
                'hotel_booking.housekeeping_menu_report',
                'base.group_user',
                'mail.group_mail_template_editor',
                'hotel_booking.group_no_payment_check_in',
                'base.group_multi_currency',
                'hotel_booking.night_audit_group',
                'hr.group_hr_user',
                'hotel_booking.out_of_order_group',
                'hotel_booking.group_pay_amount_register_payment',
                'hotel_booking_folio.group_refund_payment',
                'hotel_booking_folio.group_register_payment',
                'hotel_booking.reporting_group',
                'hotel_booking.reservation_management_group',
                'room_availability_dashboard.group_room_availability_dashboard',
                'hotel_booking.hotel_rooms_menu_group',
                'purchase.group_send_reminder',
                'account.group_show_line_subtotals_tax_excluded',
                'base.group_no_one',
                'hotel_booking.group_update_housekeeper',
                'hotel_booking.group_update_out_of_order',
                'hotel_booking_folio.group_update_charge_with_zero',
                'hotel_booking.group_update_status',
                'hotel_booking_folio.group_undo_check_out_user',
                'hotel_booking.group_booking_discount',
                'hotel_booking.group_night_audit',
                'hotel_booking.group_assign_room',
                'hotel_booking.group_change_room',
                'hotel_booking.group_amend_stay',
                'purchase.group_purchase_user',
                'hotel_booking_folio.group_daily_revenue_user',
                'hotel_booking_folio.group_undo_check_in_user',
                'point_of_sale.group_pos_user',
                'stock.group_stock_user',
                'hotel_booking_folio.group_update_room_charge_user',
                'hotel_booking.group_hotel_booking_user',
                'sales_team.group_sale_salesman_all_leads',
                'sales_team.group_sale_salesman',
                'hotel_booking.work_orders_group'
            ],
            'house': [
                'base.group_erp_manager',
                'base.group_private_addresses',
                'base.group_allow_export',
                'hotel_booking.group_hotel_booking_admin',
                'product.group_product_pricelist',
                'base.group_partner_manager',
                'hotel_booking.create_out_of_order_group',
                'hotel_booking.create_work_order_group',
                'hotel_booking.customers_contact_menu_group',
                'hotel_booking.group_dashboard_booking_status',
                'hotel_booking.folio_filter_menu_group',
                'hotel_booking.front_office_group',
                'hotel_booking.front_office_report_menu',
                'hotel_booking.housekeeping_group',
                'hotel_booking.housekeeping_menu_report',
                'base.group_user',
                'mail.group_mail_template_editor',
                'base.group_multi_currency',
                'hotel_booking.out_of_order_group',
                'room_availability_dashboard.group_room_availability_dashboard',
                'hotel_booking.hotel_rooms_menu_group',
                'purchase.group_send_reminder',
                'account.group_show_line_subtotals_tax_excluded',
                'base.group_no_one',
                'hotel_booking.group_update_housekeeper',
                'hotel_booking.group_update_out_of_order',
                'hotel_booking.group_update_status',
                'hotel_booking.group_hotel_booking_user',
                'sales_team.group_sale_salesman_all_leads',
                'sales_team.group_sale_salesman'
            ],
        }
        group_ext_ids = group_map.get(role_key, [])
        return [self.env.ref(group_xml_id).id for group_xml_id in group_ext_ids if self.env.ref(group_xml_id, raise_if_not_found=False)]

    def write(self, vals):
        res = super().write(vals)
        if 'role_type' in vals:
            for user in self:
                role = vals.get('role_type') or user.role_type
                role_group_ids = user._get_role_group_ids(role)
                print('role_group_ids', role_group_ids)
                if role_group_ids:
                    # Only add new groups; don't remove unrelated ones
                    # user.groups_id = [(4, gid) for gid in role_group_ids if gid not in user.groups_id.ids]
                    user.groups_id = [(6, 0, role_group_ids)]
        return res

    @api.model
    def create(self, vals):
        user = super().create(vals)
        role = vals.get('role_type')
        if role:
            group_ids = user._get_role_group_ids(role)
            print('role_group_ids', group_ids)
            if group_ids:
                # user.groups_id = [(4, gid) for gid in group_ids]
                user.groups_id = [(6, 0, group_ids)]
        return user
