# -*- coding: utf-8 -*-

MENU_ITEM_ICONS = {
    'Contacts': {'os_web_icon_font': 'las la-address-book', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#009CFE','os_image_icon':'Contacts.png'},
    'Apps': {'os_web_icon_font': 'las la-icons', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#485665','os_image_icon':'Apps.png'},
    'Sales': {'os_web_icon_font': 'las la-shopping-cart', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FB7A25','os_image_icon':'Sales.png'},
    'CRM': {'os_web_icon_font': 'las la-handshake', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#D51062','os_image_icon':'CRM.png'},
    'Discuss': {'os_web_icon_font': 'las la-inbox', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FACA15','os_image_icon':'Discuss.png'},
    'Calendar': {'os_web_icon_font': 'las la-calendar-check', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#1B978D','os_image_icon':'Calendar.png'},
    'Invoicing': {'os_web_icon_font': 'las la-file-invoice-dollar', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#616F39','os_image_icon':'Invoicing.png'},
    'Link Tracker': {'os_web_icon_font': 'las la-anchor', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#ABA0F9','os_image_icon':'Link_Tracker.png'},
    'Notes': {'os_web_icon_font': 'las la-clipboard', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#B6CDE8','os_image_icon':'Notes.png'},
    'Point of Sale': {'os_web_icon_font': 'las la-store-alt', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#AB47A3','os_image_icon':'POS.png'},
    'Project': {'os_web_icon_font': 'las la-rocket', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#93441A','os_image_icon':'Project.png'},
    'Inventory': {'os_web_icon_font': 'las la-dolly', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FF084B','os_image_icon':'Inventory.png'},
    'Website': {'os_web_icon_font': 'las la-globe', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#6ABEB2','os_image_icon':'Website.png'},
    'eLearning': {'os_web_icon_font': 'las la-graduation-cap', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#67944C','os_image_icon':'eLearning.png'},
    'Email Marketing': {'os_web_icon_font': 'las la-at', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#F62992','os_image_icon':'Email_Marketing.png'},
    'Events': {'os_web_icon_font': 'las la-smile', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#B58BB2','os_image_icon':'Events.png'},
    'Surveys': {'os_web_icon_font': 'las la-tasks', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#043775','os_image_icon':'Surveys.png'},
    'Purchase': {'os_web_icon_font': 'las la-money-bill-wave-alt', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FFD777','os_image_icon':'Purchase.png'},
    'Manufacturing': {'os_web_icon_font': 'las la-wrench', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#5432D3','os_image_icon':'Manufacturing.png'},
    'Maintenance': {'os_web_icon_font': 'las la-toolbox', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#526779','os_image_icon':'Maintenance.png'},
    'Repairs': {'os_web_icon_font': 'las la-tools ', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#0594D0','os_image_icon':'Repairs.png'},
    'Employees': {'os_web_icon_font': 'las la-user-friends', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#24D26D','os_image_icon':'Employees.png'},
    'Attendances': {'os_web_icon_font': 'las la-user-clock', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#A35476','os_image_icon':'Attendances.png'},
    'Recruitment': {'os_web_icon_font': 'las la-thumbs-up', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#42009E','os_image_icon':'Recruitment.png'},
    'Fleet': {'os_web_icon_font': 'las la-car', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#4ea8de','os_image_icon':'Fleet.png'},
    'Time Off': {'os_web_icon_font': 'las la-hourglass-half', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#A1C298','os_image_icon':'Time_Off.png'},
    'Expenses': {'os_web_icon_font': 'las la-hand-holding-usd', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#52057B','os_image_icon':'Expenses.png'},
    'Lunch': {'os_web_icon_font': 'las la-utensils', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#E6B325','os_image_icon':'Lunch.png'},
    'Live Chat': {'os_web_icon_font': 'las la-comments', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#F637EC','os_image_icon':'Live_Chat.png'},
    'Members': {'os_web_icon_font': 'las la-user-check', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FF00E4','os_image_icon':'Members.png'},
    'Dashboards': {'os_web_icon_font': 'las la-chart-pie', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#0E5E6F','os_image_icon':'Dashboards.png'},
    'SMS Marketing': {'os_web_icon_font': 'las la-sms', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#DA0037','os_image_icon':'SMS_Marketing.png'},
    'Settings': {'os_web_icon_font': 'las la-cogs', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#C3B091','os_image_icon':'Settings.png'},

}


MODULE_ICONS = {
    'contacts': {'os_web_icon_font': 'las la-address-book', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#009CFE','os_image_icon':'Contacts.png'},
    'sale_management': {'os_web_icon_font': 'las la-shopping-cart', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FB7A25','os_image_icon':'Sales.png'},
    'sale': {'os_web_icon_font': 'las la-shopping-cart', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FB7A25','os_image_icon':'Sales.png'},
    'crm': {'os_web_icon_font': 'las la-handshake', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#D51062','os_image_icon':'CRM.png'},
    'mail': {'os_web_icon_font': 'las la-inbox', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FACA15','os_image_icon':'Discuss.png'},
    'calendar': {'os_web_icon_font': 'las la-calendar-check', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#1B978D','os_image_icon':'Calendar.png'},
    'account': {'os_web_icon_font': 'las la-file-invoice-dollar', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#616F39','os_image_icon':'Invoicing.png'},
    'utm': {'os_web_icon_font': 'las la-anchor', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#ABA0F9','os_image_icon':'Link_Tracker.png'},
    'note': {'os_web_icon_font': 'las la-clipboard', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#B6CDE8','os_image_icon':'Notes.png'},
    'point_of_sale': {'os_web_icon_font': 'las la-store-alt', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#AB47A3','os_image_icon':'POS.png'},
    'project': {'os_web_icon_font': 'las la-rocket', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#93441A','os_image_icon':'Project.png'},
    'stock': {'os_web_icon_font': 'las la-dolly', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FF084B','os_image_icon':'Inventory.png'},
    'website': {'os_web_icon_font': 'las la-globe', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#6ABEB2','os_image_icon':'Website.png'},
    'website_slides': {'os_web_icon_font': 'las la-graduation-cap', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#67944C','os_image_icon':'eLearning.png'},
    'mass_mailing': {'os_web_icon_font': 'las la-at', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#F62992','os_image_icon':'Email_Marketing.png'},
    'event': {'os_web_icon_font': 'las la-smile', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#B58BB2','os_image_icon':'Events.png'},
    'website_event': {'os_web_icon_font': 'las la-smile', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#B58BB2','os_image_icon':'Events.png'},
    'survey': {'os_web_icon_font': 'las la-tasks', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#043775','os_image_icon':'Surveys.png'},
    'purchase': {'os_web_icon_font': 'las la-money-bill-wave-alt', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FFD777','os_image_icon':'Purchase.png'},
    'mrp': {'os_web_icon_font': 'las la-wrench', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#5432D3','os_image_icon':'Manufacturing.png'},
    'maintenance': {'os_web_icon_font': 'las la-toolbox', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#526779','os_image_icon':'Maintenance.png'},
    'repair': {'os_web_icon_font': 'las la-tools ', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#0594D0','os_image_icon':'Repairs.png'},
    'hr': {'os_web_icon_font': 'las la-user-friends', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#24D26D','os_image_icon':'Employees.png'},
    'hr_attendance': {'os_web_icon_font': 'las la-user-clock', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#A35476','os_image_icon':'Attendances.png'},
    'hr_recruitment': {'os_web_icon_font': 'las la-thumbs-up', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#42009E','os_image_icon':'Recruitment.png'},
    'fleet': {'os_web_icon_font': 'las la-car', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#4ea8de','os_image_icon':'Fleet.png'},
    'hr_holidays': {'os_web_icon_font': 'las la-hourglass-half', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#A1C298','os_image_icon':'Time_Off.png'},
    'hr_expense': {'os_web_icon_font': 'las la-hand-holding-usd', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#52057B','os_image_icon':'Expenses.png'},
    'lunch': {'os_web_icon_font': 'las la-utensils', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#E6B325','os_image_icon':'Lunch.png'},
    'im_livechat': {'os_web_icon_font': 'las la-comments', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#F637EC','os_image_icon':'Live_Chat.png'},
    'membership': {'os_web_icon_font': 'las la-user-check', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#FF00E4','os_image_icon':'Members.png'},
    'board': {'os_web_icon_font': 'las la-chart-pie', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#0E5E6F','os_image_icon':'Dashboards.png'},
    'mass_mailing_sms': {'os_web_icon_font': 'las la-sms', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#DA0037','os_image_icon':'SMS_Marketing.png'},

    'Settings': {'os_web_icon_font': 'las la-cogs', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#C3B091','os_image_icon':'Settings.png'},
    'Apps': {'os_web_icon_font': 'las la-icons', 'os_web_icon_color': '#FFFFFF', 'os_shape_color': '#485665','os_image_icon': 'Apps.png'},
}

