from . import airport_management
from . import booking_folio
from . import booking_folio_bed
from . import flight_schedule
from . import hotel_contract_management
from . import booking_package
from . import package_price
from . import extra_service
from . import hotel_booking
from . import hotel_hotel
from . import hotel_room
from . import package_contract
from . import pilgrim_booking
from . import pilgrim_management_details
from . import res_company
from . import res_partner
from . import room_type
from . import transportation_locations
from . import transportation_contract
from . import activity
from . import actual_hotel
