# -*- coding: utf-8 -*-
from . import room
from . import hotel_room_type
from . import room_status
from . import rate_type
from . import rate_plan
from . import room_type
from . import floor
from . import facility
from . import booking
from . import booking_line
from . import res_partner
from . import config
from . import account_move
from . import account_payment
from . import account_payment_method
from . import dashboard2
from . import company
from . import transfer
from . import res_users
from . import hotels
from . import pricelist
from . import services
from . import conditions
from . import purchase
from . import bed_type
from . import out_of_order_reason
from . import booking_type
from . import booking_source
from . import booking_guest
from . import booking_folio
from . import booking_discount
from . import hotel_work_order
from . import account_journal
from . import hr_employee
from . import market_segmentation
from . import booking_filter
from . import city_ledger_payment
from . import booking_filter_xlsx
from . import season_duration
from . import advance_payment
from . import settled_booking
