{
    'name': 'Tourism Hotel Booking Management',
    'version': '15.0.0',
    'description': """Hotel Management System""",
    'category': 'Base',
    'author': 'Debug Company & Codigo Technology',
    'license': 'AGPL-3',
    'depends': ['account', 'product','contacts','purchase','web_domain_field', 'barcodes', 'web', 'report_xlsx', 'report_xlsx_helper', 'hotel_booking'],
    'data': [
        'security/group.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/mail.xml',
        'views/hotel.xml',
        # 'views/floor.xml',
        'views/room.xml',
        'views/room_type.xml',
        'views/facility.xml',
        'views/service_voucher.xml',
        'views/booking.xml',
        'views/hotel_reservation_package.xml',
        'views/plane_reservation_package.xml',
        'views/bus_reservation_package.xml',
        # 'views/res_partner.xml',
        'views/account_move.xml',
        'views/account_move_line.xml',
        'views/dashboard2.xml',
        'views/transfer.xml',
        'views/conditions.xml',
        'views/services.xml',
        'views/destination.xml',
        'views/transport_package.xml',
        'views/hotel_transportation_contract.xml',
        'views/hotel_booking_transportation.xml',
        'reports/hotel_booking_transportation_report_templates.xml',
        'reports/report.xml',
        'views/email.xml',
        'reports/booking_report.xml',
        'reports/check_booking_line_report.xml',
        'reports/check_booking_line_xlsx.xml',
        'reports/booking_line_xlsx.xml',
        'reports/booking_line_report.xml',
        'reports/reservation_confirm.xml',
        # 'reports/invoice.xml',
        'reports/booking.xml',
        'views/contract.xml',
        # 'views/purchase.xml',
        'views/res_company.xml',
        'views/contract_wizard.xml',
        'views/booking_portal_template.xml',
        'views/account_payment_register.xml',
        'views/hotel_default_room.xml',
        'views/bus_type_view.xml',
        'views/plane_type_view.xml',
        'views/reservation_package.xml',
        'reports/vouchers.xml',
        'wizards/booking_line_report.xml',
        'wizards/check_booking_line_report.xml',
        'reports/hotel_transportation_contract_report.xml',
    ],
    'assets': {
        "web.assets_backend": [
            "/hotel_booking/static/src/js/barcode.js"
        ],
        'web.assets_frontend': [
            'hotel_booking/static/src/js/signature_form.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}
