{
    'name': "B2cHajj",
    'author': "Ahmed Elgamal",
    'version': '15.0.1',
    'depends': ['web', 'portal', 'hotel_booking', 'hotel_booking_folio_extend',
                'sh_whatsapp_integration_api', 'barcodes', 'widget_mobile_scan', 'web_widget_numeric_step'],
    'external_dependencies': {
        'python': ['qrcode'],
    },
    'data': [
        'data/ir_sequence.xml',
        'security/group.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/mail_template.xml',
        'views/res_partner_view.xml',
        'views/booking_package_view.xml',
        'views/hotel_booking_view.xml',
        'views/room_type_view.xml',
        'views/hotel_room.xml',
        'views/hotel_hotel_view.xml',
        'views/folio.xml',
        'views/res_company.xml',
        'views/flight_schedule_view.xml',
        'views/pilgrim_management_details_view.xml',
        'views/transportation_contract_view.xml',
        'views/portal_templates.xml',
        'views/package_contract_view.xml',
        'views/airport_management_view.xml',
        'views/hotel_contract_view.xml',
        'views/pilgrim_booking_view.xml',
        'views/package_price.xml',
        'wizards/folio_switch_bed.xml',
        'wizards/hotel_room_generate.xml',
        'wizards/hotel_room_update.xml',
        'report/pilgram_management_report.xml',
        'wizards/assign_guest_wizard.xml',
        'data/actions.xml',
        'views/transport_location.xml',
        'wizards/update_package_wizard.xml',
        'report/pilgrim_barcode_report.xml',
        'wizards/scan_pilgrim_wizard.xml',
        'wizards/pilgrim_transport.xml',
        'views/actual_hotel.xml',
        'data/cron.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
