# -*- coding: utf-8 -*-
from . import room
from . import hotel_default_room
from . import booking
from . import booking_line
from . import res_partner
from . import account_move
from . import dashboard2
from . import transfer
from . import hotels
from . import conditions
from . import purchase
from . import res_company
from . import service_voucher
from . import transportation_booking
from . import visa_booking
from . import bus_type
from . import contract_wizard
from . import plane_type
from . import hotel_contract
from . import reservation_package
from . import hotel_reservation_package
from . import plane_reservation_package
from . import bus_reservation_package
from . import destination
from . import transport_package
from . import hotel_transportation_contract
from . import hotel_booking_transportation